/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `Morphemes`;

CREATE TABLE `Morphemes` (
  `lpnr` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Morpheme` varchar(40) NOT NULL DEFAULT '',
  `Gloss` varchar(100) DEFAULT NULL,
  `VowQual` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`lpnr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `MorphToType`;

CREATE TABLE `MorphToType` (
  `lpnr` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `lpnrType` int(11) NOT NULL,
  `Morpheme` varchar(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`lpnr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `Tokens`;

CREATE TABLE `Tokens` (
  `lpnr` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `clip_file` varchar(100) NOT NULL DEFAULT '',
  `data_item` varchar(300) NOT NULL DEFAULT '',
  `som_tone` varchar(300) DEFAULT '',
  `Vowel_quality` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`lpnr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `Types`;

CREATE TABLE `Types` (
  `lpnr` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `gloss_item` varchar(300) NOT NULL DEFAULT '',
  `en_trans` varchar(300) NOT NULL DEFAULT '',
  PRIMARY KEY (`lpnr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
